name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  web-lint:
    name: Web Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run ESLint
        run: npm run lint

  python-smoke:
    name: Python Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install project (with dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Smoke test import & game registration
        run: |
          python - <<'PY'
          import pyspiel, take5bot.openspiel_take5 as mod
          pyspiel.register_game(mod.GAME_TYPE, mod.TakeFiveGame)
          g = pyspiel.load_game('take5')
          s = g.new_initial_state()
          print('Loaded take5. Initial state rows:', s._rows if hasattr(s, '_rows') else 'n/a')
          PY

      - name: Style (ruff) check (non-blocking)
        continue-on-error: true
        run: |
          if python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('ruff') else 1)"; then
            ruff check .
          else
            echo 'ruff not installed; skipping.'
          fi

      - name: Black formatting check (non-blocking)
        continue-on-error: true
        run: |
          if python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('black') else 1)"; then
            black --check .
          else
            echo 'black not installed; skipping.'
          fi
